# 如果系統有環境變數 DB_HOST，就用它；沒有就預設用 localhost
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecommerce_db}

# 如果系統有環境變數 DB_USER 和 DB_PASS，就動態帶入
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:887985}

# 自動建表改成 validate（只檢查，不自動改結構，防止洗掉線上資料）
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 從作業系統的環境變數讀取 JWT_SECRET，如果系統沒設定，則預設採用後面那一串（本地開發用）
app.jwt.secret=${JWT_SECRET:0Ig9MmtE2NM4RGECC5ECGDvFfREpT78YMjOtv7TtJW5}